version: '3.7'
services: 
  iam-manager:
      container_name: iam-manager
      image: iam_manager:jvm
      build:
        context: .
        dockerfile: ./src/main/docker/Dockerfile.jvm
      ports:
        # To receive the curls
        - 8081:8080
      volumes:
      # won't work in WINDOWS!!
      # Only works with JVM image !!
      - type: bind
        source: ./docker-conf/iam-manager/application.properties
        target: /deployments/config/application.properties
      # Saving menu.json for /menu endpoint
      - type: bind
        source: ./docker-conf/iam-manager/menu.json
        target: /resources/menu.json
      depends_on:
        - keycloak
      networks:
        - gateway_rechable
networks:
  # Containers that should be recheable by the gateway
  gateway_rechable:
    driver: bridge